version: '3.8'

services:
  g2n-mcp-gcal-ssee:
    image: jebentier/g2n-mcp-gcal-sse:latest
    environment:
      PORT: 3001
      PUBLIC_URL: https://[seu-dominio.com]
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      OAUTH_REDIRECT_PATH: /oauth/callback
    volumes:
      - gcal_tokens:/app/data
    networks:
      - cf-tunnel-network
      - app_network
    deploy:
      replicas: 1
      restart_policy:
        condition: any

volumes:
  gcal_tokens:
    external: true

networks:
  cf-tunnel-network:
    external: true
  app_network:
    external: true
